name 'awesome_customers_ubuntu'
maintainer 'Andrew Zeswitz'
maintainer_email 'andrew.zeswitz@icfi.com'
license 'all_rights'
description 'Installs/Configures awesome_customers_ubuntu'
long_description 'Installs/Configures awesome_customers_ubuntu'
version '0.1.4'

depends 'apt', '~> 3.0.0'
depends 'firewall', '~> 2.5.0'
depends 'httpd', '~> 0.3.4'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'mysql', '~> 6.1.2'
depends 'database', '~> 4.0.9'
